"""rename department

Revision ID: 9bd10b7222ed
Revises: 71f976a2b7eb
Create Date: 2025-05-11 17:26:08.002089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd10b7222ed'
down_revision = '71f976a2b7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments', 'department')
    # ### end Alembic commands ###
